--------------------------------------------------------
--  DDL for Table GW_CALENDAR
--------------------------------------------------------

  CREATE TABLE "GW_PROJECT"."GW_CALENDAR" 
   (	"CAL_TITLE" VARCHAR2(20 BYTE), 
	"CAL_MEMBER" VARCHAR2(20 BYTE), 
	"CAL_CONTENT" VARCHAR2(300 BYTE), 
	"CAL_START_DATE" DATE, 
	"CAL_END_DATE" DATE, 
	"EMP_NUM" VARCHAR2(20 BYTE), 
	"CAL_NUM" VARCHAR2(20 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Ref Constraints for Table GW_CALENDAR
--------------------------------------------------------

  ALTER TABLE "GW_PROJECT"."GW_CALENDAR" ADD FOREIGN KEY ("EMP_NUM")
	  REFERENCES "GW_PROJECT"."GW_MEMBER" ("EMP_NUM") ENABLE;

CREATE SEQUENCE cal_seq;