create table CALENDARMEMO(
	CALENDARMEMO_CONTENTS VARCHAR2(500),
	CALENDARMEMO_YEAR NUMBER,
	CALENDARMEMO_MONTH NUMBER,
	CALENDARMEMO_DAY NUMBER,
	CALENDARMEMO_NUM NUMBER,
	CALENDARMEMO_ID VARCHAR2(30),
	CALENDARMEMO_PASSWD VARCHAR2(30)
);

INSERT INTO CALENDARMEMO(CALENDARMEMO_CONTENTS, CALENDARMEMO_YEAR, CALENDARMEMO_MONTH, CALENDARMEMO_DAY)
   VALUES ('test', 2011, 6, 1)
   
select * from CALENDARMEMO

drop table calendarmemo